sudo: required
services:
  - docker

before_install:
  - docker build -t anthony9698/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true anthony9698/react-test npm test

after_success:
  - docker build -t anthony9698/multi-client ./client
  - docker build -t anthony9698/multi-nginx ./nginx
  - docker build -t anthony9698/multi-server ./server
  - docker build -t anthony9698/multi-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push anthony9698/multi-client
  - docker push anthony9698/multi-nginx
  - docker push anthony9698/multi-server
  - docker push anthony9698/multi-worker
